gha: exclude testing PHP 8 and Laravel 6
Not sure where the dependency hell problem is and how to solve it.

From the failed GHA:
```
Your requirements could not be resolved to an installable set of packages.
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v6.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.3 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts 6.x-dev (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.0 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.1 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.2 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.3 (conflict analysis result)
    - orchestra/testbench[v3.5.0, ..., 3.5.x-dev] require phpunit/phpunit ~6.0 -> satisfiable by phpunit/phpunit[6.0.0, ..., 6.5.14].
    - orchestra/testbench v4.0.1 requires phpunit/phpunit ^8.3 -> satisfiable by phpunit/phpunit[8.3.0, ..., 8.5.x-dev].
    - orchestra/testbench[v3.9.0, ..., 3.9.x-dev, v4.0.0] require phpunit/phpunit ^8.0 -> satisfiable by phpunit/phpunit[8.0.0, ..., 8.5.x-dev].
    - orchestra/testbench[v3.6.6, ..., 3.6.x-dev] require laravel/framework ~5.6.34 -> satisfiable by laravel/framework[v5.6.34, ..., 5.6.x-dev].
    - orchestra/testbench[v3.6.4, ..., v3.6.5] require laravel/framework ~5.6.13 -> satisfiable by laravel/framework[v5.6.13, ..., 5.6.x-dev].
    - orchestra/testbench v3.6.3 requires laravel/framework ~5.6.5 -> satisfiable by laravel/framework[v5.6.5, ..., 5.6.x-dev].
    - orchestra/testbench[v3.6.1, ..., v3.6.2] require laravel/framework ~5.6.4 -> satisfiable by laravel/framework[v5.6.4, ..., 5.6.x-dev].
    - orchestra/testbench v3.6.0 requires laravel/framework ~5.6.0 -> satisfiable by laravel/framework[v5.6.0, ..., 5.6.x-dev].
    - orchestra/testbench[v3.7.7, ..., 3.7.x-dev] require laravel/framework ~5.7.28 -> satisfiable by laravel/framework[v5.7.28, v5.7.29, 5.7.x-dev].
    - orchestra/testbench v3.7.6 requires laravel/framework ~5.7.14 -> satisfiable by laravel/framework[v5.7.14, ..., 5.7.x-dev].
    - orchestra/testbench[v3.7.1, ..., v3.7.5] require laravel/framework ~5.7.4 -> satisfiable by laravel/framework[v5.7.4, ..., 5.7.x-dev].
    - orchestra/testbench v3.7.0 requires laravel/framework ~5.7.0 -> satisfiable by laravel/framework[v5.7.0, ..., 5.7.x-dev].
    - orchestra/testbench[v3.8.5, ..., 3.8.x-dev] require laravel/framework ~5.8.35 -> satisfiable by laravel/framework[v5.8.35, ..., 5.8.x-dev].
    - orchestra/testbench[v3.8.3, ..., v3.8.4] require laravel/framework ~5.8.19 -> satisfiable by laravel/framework[v5.8.19, ..., 5.8.x-dev].
    - orchestra/testbench v3.8.2 requires laravel/framework ~5.8.3 -> satisfiable by laravel/framework[v5.8.3, ..., 5.8.x-dev].
    - orchestra/testbench v3.8.1 requires laravel/framework ~5.8.2 -> satisfiable by laravel/framework[v5.8.2, ..., 5.8.x-dev].
    - orchestra/testbench v3.8.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[v5.8.0, ..., 5.8.x-dev].
    - phpunit/phpunit[6.0.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - phpunit/phpunit[8.0.0, ..., 8.5.x-dev] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - illuminate/contracts[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - orchestra/testbench[v6.0.0, ..., 6.x-dev] require laravel/framework ^8.0 -> satisfiable by laravel/framework[v8.0.0, ..., 8.x-dev].
    - orchestra/testbench v5.0.2 requires laravel/framework ^7.0.6 -> satisfiable by laravel/framework[v7.0.6, ..., 7.x-dev].
    - orchestra/testbench v5.0.1 requires laravel/framework ^7.0.1 -> satisfiable by laravel/framework[v7.0.1, ..., 7.x-dev].
    - orchestra/testbench v5.0.0 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[v7.0.0, ..., 7.x-dev].
    - Only one of these can be installed: laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires illuminate/contracts ^6.0 -> satisfiable by illuminate/contracts[v6.0.0, ..., 6.x-dev], laravel/framework[v6.0.0, ..., 6.x-dev].
    - Root composer.json requires orchestra/testbench 3.5.*|3.6.*|3.7.*|3.8.*|3.9.*|4.0.*|5.0.*|^6.0 -> satisfiable by orchestra/testbench[v3.5.0, ..., 3.9.x-dev, v4.0.0, v4.0.1, v5.0.0, v5.0.1, v5.0.2, v6.0.0, ..., 6.x-dev].

  Problem 1
    - Conclusion: don't install laravel/framework v6.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.3 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts 6.x-dev (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.0 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.1 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.2 (conflict analysis result)
    - Conclusion: don't install illuminate/contracts v6.20.3 (conflict analysis result)
    - orchestra/testbench[v3.5.0, ..., 3.5.x-dev] require phpunit/phpunit ~6.0 -> satisfiable by phpunit/phpunit[6.0.0, ..., 6.5.14].
    - orchestra/testbench v4.0.1 requires phpunit/phpunit ^8.3 -> satisfiable by phpunit/phpunit[8.3.0, ..., 8.5.x-dev].
    - orchestra/testbench[v3.9.0, ..., 3.9.x-dev, v4.0.0] require phpunit/phpunit ^8.0 -> satisfiable by phpunit/phpunit[8.0.0, ..., 8.5.x-dev].
    - orchestra/testbench[v3.6.6, ..., 3.6.x-dev] require laravel/framework ~5.6.34 -> satisfiable by laravel/framework[v5.6.34, ..., 5.6.x-dev].
    - orchestra/testbench[v3.6.4, ..., v3.6.5] require laravel/framework ~5.6.13 -> satisfiable by laravel/framework[v5.6.13, ..., 5.6.x-dev].
    - orchestra/testbench v3.6.3 requires laravel/framework ~5.6.5 -> satisfiable by laravel/framework[v5.6.5, ..., 5.6.x-dev].
    - orchestra/testbench[v3.6.1, ..., v3.6.2] require laravel/framework ~5.6.4 -> satisfiable by laravel/framework[v5.6.4, ..., 5.6.x-dev].
    - orchestra/testbench v3.6.0 requires laravel/framework ~5.6.0 -> satisfiable by laravel/framework[v5.6.0, ..., 5.6.x-dev].
    - orchestra/testbench[v3.7.7, ..., 3.7.x-dev] require laravel/framework ~5.7.28 -> satisfiable by laravel/framework[v5.7.28, v5.7.29, 5.7.x-dev].
    - orchestra/testbench v3.7.6 requires laravel/framework ~5.7.14 -> satisfiable by laravel/framework[v5.7.14, ..., 5.7.x-dev].
    - orchestra/testbench[v3.7.1, ..., v3.7.5] require laravel/framework ~5.7.4 -> satisfiable by laravel/framework[v5.7.4, ..., 5.7.x-dev].
    - orchestra/testbench v3.7.0 requires laravel/framework ~5.7.0 -> satisfiable by laravel/framework[v5.7.0, ..., 5.7.x-dev].
    - orchestra/testbench[v3.8.5, ..., 3.8.x-dev] require laravel/framework ~5.8.35 -> satisfiable by laravel/framework[v5.8.35, ..., 5.8.x-dev].
    - orchestra/testbench[v3.8.3, ..., v3.8.4] require laravel/framework ~5.8.19 -> satisfiable by laravel/framework[v5.8.19, ..., 5.8.x-dev].
    - orchestra/testbench v3.8.2 requires laravel/framework ~5.8.3 -> satisfiable by laravel/framework[v5.8.3, ..., 5.8.x-dev].
    - orchestra/testbench v3.8.1 requires laravel/framework ~5.8.2 -> satisfiable by laravel/framework[v5.8.2, ..., 5.8.x-dev].
    - orchestra/testbench v3.8.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[v5.8.0, ..., 5.8.x-dev].
    - phpunit/phpunit[6.0.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - phpunit/phpunit[8.0.0, ..., 8.5.x-dev] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - illuminate/contracts[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - laravel/framework[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - orchestra/testbench[v6.0.0, ..., 6.x-dev] require laravel/framework ^8.0 -> satisfiable by laravel/framework[v8.0.0, ..., 8.x-dev].
    - orchestra/testbench v5.0.2 requires laravel/framework ^7.0.6 -> satisfiable by laravel/framework[v7.0.6, ..., 7.x-dev].
    - orchestra/testbench v5.0.1 requires laravel/framework ^7.0.1 -> satisfiable by laravel/framework[v7.0.1, ..., 7.x-dev].
    - orchestra/testbench v5.0.0 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[v7.0.0, ..., 7.x-dev].
    - Only one of these can be installed: laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires illuminate/contracts ^6.0 -> satisfiable by illuminate/contracts[v6.0.0, ..., 6.x-dev], laravel/framework[v6.0.0, ..., 6.x-dev].
    - Root composer.json requires orchestra/testbench 3.5.*|3.6.*|3.7.*|3.8.*|3.9.*|4.0.*|5.0.*|^6.0 -> satisfiable by orchestra/testbench[v3.5.0, ..., 3.9.x-dev, v4.0.0, v4.0.1, v5.0.0, v5.0.1, v5.0.2, v6.0.0, ..., 6.x-dev].

Error: Process completed with exit code 2.
```